#!/usr/bin/env python3
"""
Конвертер: наш скилл (SKILL.md + references/) или папка промптов -> OWUI-тулза.

Идея: скилл это знание («как правильно делать X») + иногда шаги. Модели в чате его удобнее
всего отдать как ТУЛЗУ, у которой один метод на раздел: модель сама решает, когда подтянуть
инструкцию, и не таскает весь текст в системном промпте.

Usage:
  ./skill_to_tool.py ~/.claude/skills/diagram-design --id diagram_design --install
  ./skill_to_tool.py ~/.claude/skills/gpu-watch --id gpu_watch --max-chars 6000 > gpu_watch_tool.py

Что делает:
  1. читает SKILL.md (frontmatter name/description) и references/*.md;
  2. на каждый reference делает метод get_<slug>() с docstring из первого абзаца;
  3. добавляет метод overview() с сутью SKILL.md;
  4. режет длинные тексты по --max-chars (модель всё равно не переварит простыню);
  5. с --install ставит тулзу через API OWUI (как install_tool.sh).

Ограничение: это отдаёт ЗНАНИЕ, а не исполнение. Если скиллу нужны действия (запустить скрипт,
сходить в YT), дописывай методы руками поверх сгенерированного файла.
"""
import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

FM = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.S)


def parse_front_matter(text):
    m = FM.match(text)
    if not m:
        return {}, text
    meta = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith(" "):
            k, v = line.split(":", 1)
            meta[k.strip()] = v.strip().strip("'\"")
    return meta, text[m.end():]


def slugify(name):
    s = re.sub(r"[^a-zA-Z0-9]+", "_", name.lower()).strip("_")
    return re.sub(r"_+", "_", s) or "section"


def first_sentence(text, limit=180):
    body = re.sub(r"^#.*$", "", text, flags=re.M).strip()
    body = re.sub(r"\s+", " ", body)
    cut = body[:limit]
    return (cut.rsplit(".", 1)[0] + ".") if "." in cut else cut


def py_literal(text, max_chars):
    if len(text) > max_chars:
        text = text[:max_chars].rsplit("\n", 1)[0] + "\n\n[...обрезано, полный текст в скилле]"
    return json.dumps(text, ensure_ascii=False)


def build(skill_dir: Path, tool_id: str, max_chars: int):
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        sys.exit(f"нет {skill_md}")
    meta, body = parse_front_matter(skill_md.read_text(encoding="utf-8"))
    name = meta.get("name", skill_dir.name)
    desc = re.sub(r"\s+", " ", meta.get("description", "")).strip()[:400]

    sections = []
    refs = sorted((skill_dir / "references").glob("*.md")) if (skill_dir / "references").is_dir() else []
    for ref in refs:
        txt = ref.read_text(encoding="utf-8")
        _, rbody = parse_front_matter(txt)
        title = next((l.lstrip("# ").strip() for l in rbody.splitlines() if l.startswith("#")), ref.stem)
        sections.append({
            "slug": slugify(ref.stem),
            "title": title,
            "summary": first_sentence(rbody),
            "content": rbody.strip(),
        })

    out = [
        '"""',
        f"title: {name}",
        "author: agents-team (generated by skill_to_tool.py)",
        "version: 0.1.0",
        f"description: {desc or ('Знание из скилла ' + name)}",
        '"""',
        "# СГЕНЕРИРОВАНО из скилла: " + str(skill_dir),
        "# Отдаёт ЗНАНИЕ (инструкции/правила). Действия дописывай методами руками.",
        "from pydantic import BaseModel, Field",
        "",
        "",
        "class Tools:",
        "    class Valves(BaseModel):",
        "        ENABLED: bool = Field(default=True, description='выключатель тулзы')",
        "",
        "    def __init__(self):",
        "        self.valves = self.Valves()",
        "",
        "    def overview(self) -> str:",
        '        """',
        f"        Обзор: {desc or name}. Вызывать первым, когда вопрос касается темы «{name}», чтобы понять какие разделы есть.",
        '        """',
        f"        return {py_literal(body.strip(), max_chars)}",
        "",
    ]
    for s in sections:
        out += [
            f"    def get_{s['slug']}(self) -> str:",
            '        """',
            f"        {s['title']}. {s['summary']}",
            '        """',
            f"        return {py_literal(s['content'], max_chars)}",
            "",
        ]
    return "\n".join(out), name, desc, [s["slug"] for s in sections]


def install(code: str, tool_id: str, name: str, desc: str, container: str, host: str):
    tok = subprocess.check_output([
        "docker", "exec", "-i", container, "python3", "-c",
        "import jwt,sqlite3;c=sqlite3.connect('/app/backend/data/webui.db');"
        "u=c.execute(\"select id from user where role='admin'\").fetchone()[0];"
        "print(jwt.encode({'id':u},open('/app/backend/.webui_secret_key').read().strip(),algorithm='HS256'))"
    ], text=True).strip()
    # тело кладём в файл: у больших скиллов JSON не влезает в argv ("Argument list too long")
    import tempfile
    body = json.dumps({"id": tool_id, "name": name,
                       "meta": {"description": desc[:200]}, "content": code})
    tmp = tempfile.NamedTemporaryFile("w", suffix=".json", delete=False, encoding="utf-8")
    tmp.write(body)
    tmp.close()
    for ep in (f"/api/v1/tools/id/{tool_id}/update", "/api/v1/tools/create"):
        p = subprocess.run(["curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
                            "-X", "POST", "-H", f"Authorization: Bearer {tok}",
                            "-H", "Content-Type: application/json",
                            f"{host}{ep}", "--data", "@" + tmp.name], capture_output=True, text=True)
        print(f"{ep} -> HTTP={p.stdout}", file=sys.stderr)
        if p.stdout.strip() == "200":
            break
    subprocess.run(["curl", "-s", "-o", "/dev/null", "-H", f"Authorization: Bearer {tok}",
                    f"{host}/api/models?refresh=true"])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("skill_dir")
    ap.add_argument("--id", required=True, help="id тулзы в OWUI, напр. diagram_design")
    ap.add_argument("--max-chars", type=int, default=8000, help="потолок текста на метод")
    ap.add_argument("--install", action="store_true")
    ap.add_argument("--container", default="open-webui")
    ap.add_argument("--host", default="http://[::1]:3000")
    a = ap.parse_args()

    code, name, desc, slugs = build(Path(a.skill_dir).expanduser(), a.id, a.max_chars)
    if a.install:
        install(code, a.id, name, desc, a.container, a.host)
        print(f"установлено: {a.id} (методы: overview, " + ", ".join("get_" + s for s in slugs) + ")",
              file=sys.stderr)
    else:
        print(code)


if __name__ == "__main__":
    main()
